version: "3.6"
services:
 wordpress:
   image: wordpress:latest
   container_name: themewordpress
   volumes:
      - wpfiles:/var/www/html
      - ./wp-content:/var/www/html/wp-content
   environment:
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_TABLE_PREFIX=wp_
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=password
   depends_on:
     - db
     - phpmyadmin
   restart: always
   ports:
     - 8089:80
   networks:
     - wpnet
 
 db:
   image: mariadb:latest
   container_name: themedb
   volumes:
     - db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=wordpress
   networks:
     - wpnet
   restart: always
 
 phpmyadmin:
   depends_on:
     - db
   image: phpmyadmin/phpmyadmin:latest
   container_name: themephpmyadmin
   restart: always
   ports:
     - 8181:80
   networks:
     - wpnet

   environment:
     PMA_HOST: db
     MYSQL_ROOT_PASSWORD: password
 
volumes:
  wpdata:
  wpfiles:

networks:
  wpnet: